server:
  port: ${PORT:8100}

name: ' Marvel World '

security:
  basic:
    enabled: false
management:
  security:
    enabled: false

endpoints:
  health:
    sensitive: false
  shutdown:
    enabled: true

spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:mysql://${sqlserver:localhost}:3306/demo
    username: demo_user
    password: demo_pass
    driver-class-name: com.mysql.jdbc.Driver